image: docker:18-git

variables:
  GIT_STRATEGY: clone

default:
  tags:
    - procurex

#before_script:
#  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

prepare:
  script:
    - cp /home/gitlab-runner/env-sso .env
    - docker stop $(docker ps -a -q --filter ancestor=procurex-sso --format="{{.ID}}")

build:
  script:
    - docker build -t procurex-sso .
    
deploy:
  script:
    - docker run -d --network=procurex-net --restart unless-stopped -p 9001:9000 procurex-sso
  
