image: docker:18-git

#services:
#  - docker:18-dind
  
#variables:
#  DOCKER_HOST: tcp://docker:2375/
#  DOCKER_DRIVER: overlay2

variables:
  GIT_STRATEGY: clone

default:
  tags:
    - procurex

#before_script:
#  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_image:
  script:
    #- docker build -t registry.gitlab.com/itdevpi/procurex/sso-service .
    #- docker push registry.gitlab.com/itdevpi/procurex/sso-service
    - docker build -t sso-procurex-docker .
    - docker run -d -p 9001:9000 --network=host sso-procurex-docker

