image: docker:18-git

variables:
  GIT_STRATEGY: clone

default:
  tags:
    - procurex

stages:
  - prepare
  - build
  - deploy
  - test


#before_script:
#  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_prepare:
  stage: prepare
  only:
    - main
  script:
    - cp /home/gitlab-runner/env-sso .env
    - docker stop $(docker ps -a -q --filter ancestor=procurex-sso --format="{{.ID}}") || true
    - docker rmi -f $(docker images -f "dangling=true" -q) || true

build_image:
  stage: build
  only:
    - main
  script:
    - docker build -t procurex-sso .

build_deploy:
  stage: deploy
  only:
    - main
  script:
    - docker run -d --network=procurex-net --restart unless-stopped -p 9001:9000 procurex-sso

build_test:
  stage: test
  only:
    - main
  script:
    - echo "Unit Test"
#    - docker exec -it $(docker ps -a -q --filter ancestor=procurex-sso --format="{{.ID}}") php artisan test


