image: docker:18-git

variables:
  GIT_STRATEGY: clone

default:
  tags:
    - procurex

#before_script:
#  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_image:
  script:
    - cp /home/gitlab-runner/env-sso .env
    - docker stop $(docker ps -a -q --filter ancestor=procurex-sso --format="{{.ID}}") || true
    - docker rmi -f $(docker images -f "dangling=true" -q) || true
    - docker build -t procurex-sso .
    - docker run -d --network=procurex-net --restart unless-stopped -p 9001:9000 procurex-sso
    
  
