image: docker:latest

services:
  - docker:dind
  
default:
  tags:
    - procurex

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_image:
  script:
    - docker build .
